# Список репозиториев для синхронизации
repositories:
  - name: "accounting"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/backend/accounting.git"
    local_path: "accounting"

  - name: "accounting-external-api"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/backend/accounting-external-api.git"
    local_path: "accounting-external-api"

  - name: "auth"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/backend/auth.git"
    local_path: "auth"

  - name: "crm"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/backend/crm.git"
    local_path: "crm"

  - name: "crm-external-integrations"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/backend/crm-external-integrations.git"
    local_path: "crm-external-integrations"

  - name: "customers"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/backend/customers.git"
    local_path: "customers"

  - name: "utils"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/backend/utils.git"
    local_path: "utils"

  - name: "qa_backend"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/qa/backend.git"
    local_path: "qa_backend"

  - name: "dream-island-front"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/dream-island-front.git"
    local_path: "dream-island-front"

  - name: "n8n"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/n8n.git"
    local_path: "n8n"

  - name: "swagger-prj"
    url: "https://<YOUR_PAT_PLACEHOLDER>@git.siberian.pro/dream-island/swagger-prj.git"
    local_path: "swagger-prj"
